theme: jekyll-theme-slate
lang: ja-JP
title: '<a href="https://shellgei.github.io/info/" style="color:white">シェル芸の情報を集めるサイト</a>'
#description: このサイトのリポジトリ<a href="https://github.com/shellgei/info">shellgei/info</a>をいじってプルリクください
markdown: kramdown
highlighter: rouge
