theme: jekyll-theme-slate
lang: ja-JP
title: '<a href="/ShellGeiData/" style="color:white">シェル芸の情報を集めるサイト</a>'
description: このサイトのリポジトリ<a href="https://github.com/shellgei/info">shellgei/info</a>をいじって適当にプルリクください
markdown: kramdown
highlighter: rouge
